development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: app_development
  pool: 5
  username: postgres
  password: church
  template: template0

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: app_test
  pool: 5
  username: postgres
  password: church
  template: template0


production:
  adapter: postgresql
  database: app_production
  pool: 5
  timeout: 5000
  template: template0
